version: '3.4'

services:
    frontend:
        image: frontend
        command: npm run start:dev
        build:
            context: .
            dockerfile: ./Dockerfile
        environment:
            NODE_ENV: development
        ports:
            - 3000:3000
        volumes:
            - .:/usr/src/app
