import { NextPage } from 'next';
import Head from 'next/head';
import MemberPortrait from '../components/pages/about/member-portrait/MemberPortrait';
import TechnologyIcon from '../components/pages/about/technology-icon/TechnologyIcon';
import styles from '../styles/AboutPage.module.scss';

/**
 * Component representing the page on the `/about` endpoint.
 */
const AboutPage: NextPage = () => {
	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className={styles.container}>
				<main>
					<section className={styles.about__section}>
						<h1 className={styles.title}>About us</h1>

						<p className={styles.about__description}>
							This website was designed by software engineering
							students at ÉTS as part of their end-of-study
							project. To access the project’s documentation or
							for more infromation about the resources used,
							please click on one of the links below.
						</p>
					</section>
				</main>

				<section className={styles.technologies__section}>
					<h2 className={styles.technologies__title}>Technologies</h2>

					<div className={styles.technologies__container}>
						<TechnologyIcon
							name="GitHub"
							src="/github.svg"
							href="#"
						/>

						<TechnologyIcon
							name="StackExchange"
							src="/WebsiteIcon.svg"
							href="https://api.stackexchange.com/docs"
						/>

						<TechnologyIcon
							name="tRPC"
							src="/trpc.svg"
							href="https://trpc.io/docs/v10"
						/>
					</div>
				</section>

				<section className={styles.team__section}>
					<h2 className={styles.team__title}>Meet our team</h2>

					<div className={styles.team__container}>
						<MemberPortrait
							memberName="Jérémy Lalonde"
							src="/user.svg"
							href="#"
						/>

						<MemberPortrait
							memberName="Hamza Laghrieb"
							src="/user.svg"
							href="#"
						/>

						<MemberPortrait
							memberName="Loïc Léger"
							src="/user.svg"
							href="#"
						/>

						<MemberPortrait
							memberName="Gabriel Roberge"
							src="/user.svg"
							href="#"
						/>

						<MemberPortrait
							memberName="Gabriel Somma"
							src="/user.svg"
							href="#"
						/>
					</div>
				</section>
			</div>
		</>
	);
};

export default AboutPage;
