import SearchIcon from '@mui/icons-material/Search';
import { SelectChangeEvent } from '@mui/material';
import type { NextPage } from 'next';
import Head from 'next/head';
import { useRouter } from 'next/router';
import { ChangeEvent, FormEvent, useCallback, useState } from 'react';
import Button from '../components/common/button/Button';
import Dropdown from '../components/form/dropdown/Dropdown';
import TextInput from '../components/form/text-input/TextInput';
import { SearchQuery } from '../lib/SearchQuery';
import { trpc } from '../utils/trpc';

const HomePage: NextPage = () => {
	const router = useRouter();
	const { data } = trpc.technologies.mockDropdown.useQuery();
	const [searchText, setSearchText] = useState('');
	const [technology, setTechnology] = useState('');

	const onFormSubmit = useCallback(
		async (e: FormEvent<HTMLFormElement>) => {
			e.preventDefault();
			const trimmedSearchText = searchText.trim();
			const trimmedTechnology = technology.trim();
			if (!trimmedSearchText) return;
			if (!trimmedTechnology) return;
			const searchQuery = new SearchQuery(
				trimmedSearchText,
				trimmedTechnology,
			);
			router.push(searchQuery.getUrl());
		},
		[router, searchText, technology],
	);

	const onSearchTextChange = useCallback(
		(e: ChangeEvent<HTMLInputElement>) => {
			setSearchText(e.target.value);
		},
		[],
	);

	const onTechnologyChange = useCallback((e: SelectChangeEvent<string>) => {
		setTechnology(e.target.value);
	}, []);

	return (
		<>
			<Head>
				<title>Create T3 App</title>
				<meta name="description" content="Generated by create-t3-app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<div className="container mx-auto flex max-w-2xl flex-1 flex-col justify-center">
				<div className="flex justify-center">Logo</div>

				<main className="w-full">
					<section>
						<form
							onSubmit={onFormSubmit}
							className="flex flex-col gap-4"
						>
							<TextInput
								name="search"
								onChange={onSearchTextChange}
								placeholder="Search..."
								required
								type="text"
							/>

							<div className="flex flex-row flex-wrap justify-center gap-2">
								<div className="max-w-[16rem] flex-1">
									<Dropdown
										label="Technology"
										name="technology"
										onChange={onTechnologyChange}
										options={data?.technologies}
										required
									/>
								</div>

								<Button
									borderRadius="rounded-full"
									type="submit"
								>
									<SearchIcon />
								</Button>
							</div>
						</form>
					</section>
				</main>
			</div>
		</>
	);
};

export default HomePage;
